<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Dell" name="hospitalManagementPack.NewTestHospital" tests="12" failures="0" timestamp="2020-08-28T09:46:10 IST" time="54.757" errors="1">
  <testcase name="login" time="8.141" classname="hospitalManagementPack.NewTestHospital"/>
  <system-out/>
  <testcase name="dashboardValidation" time="13.935" classname="hospitalManagementPack.NewTestHospital"/>
  <system-out/>
  <testcase name="DoctorsValidation" time="6.594" classname="hospitalManagementPack.NewTestHospital">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at hospitalManagementPack.NewTestHospital.DoctorsValidation(NewTestHospital.java:88)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- DoctorsValidation -->
  <system-out/>
  <testcase name="usersVlidation" time="2.602" classname="hospitalManagementPack.NewTestHospital"/>
  <system-out/>
  <testcase name="patientsVlidation" time="2.649" classname="hospitalManagementPack.NewTestHospital"/>
  <system-out/>
  <testcase name="appointmentVlidation" time="1.354" classname="hospitalManagementPack.NewTestHospital"/>
  <system-out/>
  <testcase name="contactsVlidation" time="5.232" classname="hospitalManagementPack.NewTestHospital"/>
  <system-out/>
  <testcase name="doctorSectionVlidation" time="1.498" classname="hospitalManagementPack.NewTestHospital"/>
  <system-out/>
  <testcase name="userSectionVlidation" time="1.505" classname="hospitalManagementPack.NewTestHospital"/>
  <system-out/>
  <testcase name="patientSearchValidation" time="1.564" classname="hospitalManagementPack.NewTestHospital"/>
  <system-out/>
  <testcase name="reportsVlidation" time="8.258" classname="hospitalManagementPack.NewTestHospital"/>
  <system-out/>
  <testcase name="logoutValidation" time="1.425" classname="hospitalManagementPack.NewTestHospital"/>
  <system-out/>
</testsuite> <!-- hospitalManagementPack.NewTestHospital -->
